import type { Metadata } from "next";
import "./globals.css";
import { UIProvider } from "../components/UiContext";
import { SidebarProvider } from "../components/ContextProvider"; // 👈 import SidebarProvider

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <UIProvider>
          <SidebarProvider>{children}</SidebarProvider>
        </UIProvider>
      </body>
    </html>
  );
}
